import esbuild from 'esbuild';
import process from 'process';
import { builtinModules } from 'node:module';
import { copyFileSync, mkdirSync, readFileSync } from 'node:fs';
import { dirname } from 'node:path';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === 'production';

// ビルド先ディレクトリを環境変数とマニフェストから取得
const manifest = JSON.parse(readFileSync('manifest.json', 'utf8'));
const { id } = manifest;
const outDir = process.env.OBSIDIAN_VAULT_PATH
    ? `${process.env.OBSIDIAN_VAULT_PATH}/.obsidian/plugins/${id}`
    : ".";

// マニフェストとスタイルシートをビルド先ディレクトリにコピーするプラグイン
const copyPlugin = {
    name: "copy-manifest-and-styles",
    setup(build) {
        build.onEnd(() => {
            const outDir = dirname(build.initialOptions.outfile);
            mkdirSync(outDir, { recursive: true });
            copyFileSync("manifest.json", `${outDir}/manifest.json`);
            try {
                copyFileSync("styles.css", `${outDir}/styles.css`);
            } catch {
                // styles.cssがない場合はスキップ
            }
        });
    },
};

const context = await esbuild.context({
    banner: {
        js: banner,
    },
    entryPoints: ['src/main.ts'],
    bundle: true,
    loader: {
        ".tsx": "tsx",
    },
    external: [
        'obsidian',
        'electron',
        '@codemirror/autocomplete',
        '@codemirror/collab',
        '@codemirror/commands',
        '@codemirror/language',
        '@codemirror/lint',
        '@codemirror/search',
        '@codemirror/state',
        '@codemirror/view',
        '@lezer/common',
        '@lezer/highlight',
        '@lezer/lr',
        ...builtinModules,
    ],
    format: 'cjs',
    target: 'es2021',
    logLevel: 'info',
    sourcemap: prod ? false : 'inline',
    treeShaking: true,
    outfile: `${outDir}/main.js`,
    minify: prod,
    plugins: [copyPlugin],
});

if (prod) {
    await context.rebuild();
    process.exit(0);
} else {
    await context.watch();
}
